from typing import Protocol


class VectorStore(Protocol):
    def add(
        self,
        ids: list[str],
        embeddings: list[list[float]],
        documents: list[str],
        metadatas: list[dict],
    ) -> None: ...

    def query(
        self, embedding: list[float], top_k: int, where: dict | None = None
    ) -> list[dict]: ...

    def count(self) -> int: ...

    def get_by_source(self, source: str) -> list[dict]: ...

    def list_sources(self) -> list[str]: ...

    def list_documents(self) -> list[dict]: ...

    def list_folders(self) -> list[str]: ...

    def delete_source(self, source: str) -> None: ...

    def move_source(self, source: str, new_folder: str) -> None: ...

    def rename_folder(self, old_folder: str, new_folder: str) -> None: ...

    def delete_folder(self, folder: str) -> None: ...
